# base image
FROM node:12.2.0-alpine

# set working directory
WORKDIR /client

# install and cache app dependencies
COPY . .
RUN npm install yarn -g --silent
RUN yarn install
RUN yarn build

# start app
CMD ["yarn", "serve"]