version: '3'
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: client
    hostname: client
    ports:
      - '3000:3000'
    restart: unless-stopped
